version: 0.2

env:
  variables:
    ImageName: flask-app

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767397832363.dkr.ecr.us-east-1.amazonaws.com
      - echo Login succeeded.

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ImageName -f ./Dockerfile .

  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag $ImageName:latest 767397832363.dkr.ecr.us-east-1.amazonaws.com/$ImageName:latest
      - echo Pushing the Docker image to ECR...
      - docker push 767397832363.dkr.ecr.us-east-1.amazonaws.com/$ImageName:latest
      - echo Build completed successfully.

artifacts:
  files:
    - Dockerfile
    - app.py
    - app1.py

