version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767397832363.dkr.ecr.us-east-1.amazonaws.com
      - export REPOSITORY_NAME="flask-app"  # No spaces, use hyphens instead
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Repository Name: $REPOSITORY_NAME"
      - echo "Image Tag: $IMAGE_TAG"
  build:
    commands:
      - echo Building Docker image...
      - docker build -t "$REPOSITORY_NAME:$IMAGE_TAG" .
      - docker tag "$REPOSITORY_NAME:$IMAGE_TAG" "767397832363.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG"
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push "767397832363.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG"
artifacts:
  files:
    - app.py
    - Dockerfile
